# Generated by Django 4.0.2 on 2022-04-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0002_rename_name_contact_username_remove_contact_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumber',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='username',
            new_name='password',
        ),
    ]
