# Generated by Django 4.0.2 on 2022-04-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0003_rename_phonenumber_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='password',
            new_name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
