# Generated by Django 4.0.2 on 2022-04-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0004_rename_password_contact_email_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('repeatpassword', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
